/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.ad.kalkulator;

import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        am_jPanel = new javax.swing.JPanel();
        am_jTextField_l1 = new javax.swing.JTextField();
        am_jTextField_l2 = new javax.swing.JTextField();
        am_jLabel_l1 = new javax.swing.JLabel();
        am_jLabel_l2 = new javax.swing.JLabel();
        am_jLabel_dzialanie = new javax.swing.JLabel();
        am_jButton_dodawanie = new javax.swing.JButton();
        am_jButton_odejmowanie = new javax.swing.JButton();
        am_jButton_mnozenie = new javax.swing.JButton();
        am_jButton_dzielenie = new javax.swing.JButton();
        am_jTextField_wynik = new javax.swing.JTextField();
        am_jLabel_wynik = new javax.swing.JLabel();
        am_jMenuBar = new javax.swing.JMenuBar();
        am_jMenu_plik = new javax.swing.JMenu();
        am_jCheckBoxMenuItem_historia = new javax.swing.JCheckBoxMenuItem();
        am_jMenuItem_close = new javax.swing.JMenuItem();
        am_jMenu_tool = new javax.swing.JMenu();
        am_jMenuItem_iledni = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        am_jPanel.setBackground(new java.awt.Color(0, 0, 0));

        am_jTextField_l1.setBackground(new java.awt.Color(0, 0, 102));
        am_jTextField_l1.setForeground(new java.awt.Color(0, 255, 255));

        am_jTextField_l2.setBackground(new java.awt.Color(0, 0, 102));
        am_jTextField_l2.setForeground(new java.awt.Color(0, 255, 255));

        am_jLabel_l1.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_l1.setText("Pierwsza liczba:");

        am_jLabel_l2.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_l2.setText("Druga liczba:");

        am_jLabel_dzialanie.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_dzialanie.setText("Wybierz dzialanie");

        am_jButton_dodawanie.setBackground(new java.awt.Color(0, 0, 102));
        am_jButton_dodawanie.setForeground(new java.awt.Color(0, 255, 255));
        am_jButton_dodawanie.setText("Dodawanie");
        am_jButton_dodawanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jButton_dodawanieActionPerformed(evt);
            }
        });

        am_jButton_odejmowanie.setBackground(new java.awt.Color(0, 0, 102));
        am_jButton_odejmowanie.setForeground(new java.awt.Color(0, 255, 255));
        am_jButton_odejmowanie.setText("Odejmowanie");
        am_jButton_odejmowanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jButton_odejmowanieActionPerformed(evt);
            }
        });

        am_jButton_mnozenie.setBackground(new java.awt.Color(0, 0, 102));
        am_jButton_mnozenie.setForeground(new java.awt.Color(0, 255, 255));
        am_jButton_mnozenie.setText("Mnozenie");
        am_jButton_mnozenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jButton_mnozenieActionPerformed(evt);
            }
        });

        am_jButton_dzielenie.setBackground(new java.awt.Color(0, 0, 102));
        am_jButton_dzielenie.setForeground(new java.awt.Color(0, 255, 255));
        am_jButton_dzielenie.setText("Dzielenie");
        am_jButton_dzielenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jButton_dzielenieActionPerformed(evt);
            }
        });

        am_jTextField_wynik.setBackground(new java.awt.Color(0, 0, 102));
        am_jTextField_wynik.setForeground(new java.awt.Color(0, 255, 255));

        am_jLabel_wynik.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_wynik.setText("Wynik");

        javax.swing.GroupLayout am_jPanelLayout = new javax.swing.GroupLayout(am_jPanel);
        am_jPanel.setLayout(am_jPanelLayout);
        am_jPanelLayout.setHorizontalGroup(
            am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(am_jPanelLayout.createSequentialGroup()
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(am_jButton_dodawanie, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(am_jPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(am_jLabel_l1)
                                    .addComponent(am_jLabel_l2))
                                .addGap(18, 18, 18)
                                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(am_jTextField_l2)
                                    .addComponent(am_jButton_odejmowanie, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(am_jTextField_l1)))
                            .addGroup(am_jPanelLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(am_jLabel_dzialanie)))
                        .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(am_jButton_dzielenie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(am_jButton_mnozenie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(am_jPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(am_jLabel_wynik))
                    .addGroup(am_jPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(am_jTextField_wynik, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        am_jPanelLayout.setVerticalGroup(
            am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(am_jPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(am_jLabel_l1)
                    .addComponent(am_jTextField_l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(am_jTextField_l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(am_jLabel_l2))
                .addGap(27, 27, 27)
                .addComponent(am_jLabel_dzialanie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(am_jButton_dodawanie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jButton_odejmowanie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jButton_mnozenie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jButton_dzielenie)
                .addGap(18, 18, 18)
                .addComponent(am_jLabel_wynik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(am_jTextField_wynik, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        am_jMenuBar.setBackground(new java.awt.Color(51, 51, 51));

        am_jMenu_plik.setText("Plik");

        am_jCheckBoxMenuItem_historia.setSelected(true);
        am_jCheckBoxMenuItem_historia.setText("Historia działań");
        am_jMenu_plik.add(am_jCheckBoxMenuItem_historia);

        am_jMenuItem_close.setText("Zamknij");
        am_jMenuItem_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jMenuItem_closeActionPerformed(evt);
            }
        });
        am_jMenu_plik.add(am_jMenuItem_close);

        am_jMenuBar.add(am_jMenu_plik);

        am_jMenu_tool.setText("Tools");

        am_jMenuItem_iledni.setText("Ile dni pomiędzy datami");
        am_jMenuItem_iledni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jMenuItem_iledniActionPerformed(evt);
            }
        });
        am_jMenu_tool.add(am_jMenuItem_iledni);

        am_jMenuBar.add(am_jMenu_tool);

        setJMenuBar(am_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void am_jButton_dodawanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jButton_dodawanieActionPerformed
        int l1 = Integer.parseInt(am_jTextField_l1.getText());
        int l2 = Integer.parseInt(am_jTextField_l2.getText());
        int wynik = l1+l2;
        am_jTextField_wynik.setText(""+wynik);
    }//GEN-LAST:event_am_jButton_dodawanieActionPerformed

    private void am_jButton_odejmowanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jButton_odejmowanieActionPerformed
        int l1 = Integer.parseInt(am_jTextField_l1.getText());
        int l2 = Integer.parseInt(am_jTextField_l2.getText());
        int wynik = l1-l2;
        am_jTextField_wynik.setText(""+wynik);
    }//GEN-LAST:event_am_jButton_odejmowanieActionPerformed

    private void am_jButton_mnozenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jButton_mnozenieActionPerformed
        int l1 = Integer.parseInt(am_jTextField_l1.getText());
        int l2 = Integer.parseInt(am_jTextField_l2.getText());
        int wynik = l1*l2;
        am_jTextField_wynik.setText(""+wynik);
    }//GEN-LAST:event_am_jButton_mnozenieActionPerformed

    private void am_jButton_dzielenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jButton_dzielenieActionPerformed
        double l1 = Integer.parseInt(am_jTextField_l1.getText());
        double l2 = Integer.parseInt(am_jTextField_l2.getText());
        double wynik = l1/l2;
        am_jTextField_wynik.setText(""+wynik);
    }//GEN-LAST:event_am_jButton_dzielenieActionPerformed

    private void am_jMenuItem_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jMenuItem_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_am_jMenuItem_closeActionPerformed

    private void am_jMenuItem_iledniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jMenuItem_iledniActionPerformed
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MM yyyy");
        JOptionPane.showInputDialog("Wprowadź datę w formacie dd mm yyyy np. 01 02 2021");
    }//GEN-LAST:event_am_jMenuItem_iledniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Kalkulator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton am_jButton_dodawanie;
    private javax.swing.JButton am_jButton_dzielenie;
    private javax.swing.JButton am_jButton_mnozenie;
    private javax.swing.JButton am_jButton_odejmowanie;
    private javax.swing.JCheckBoxMenuItem am_jCheckBoxMenuItem_historia;
    private javax.swing.JLabel am_jLabel_dzialanie;
    private javax.swing.JLabel am_jLabel_l1;
    private javax.swing.JLabel am_jLabel_l2;
    private javax.swing.JLabel am_jLabel_wynik;
    private javax.swing.JMenuBar am_jMenuBar;
    private javax.swing.JMenuItem am_jMenuItem_close;
    private javax.swing.JMenuItem am_jMenuItem_iledni;
    private javax.swing.JMenu am_jMenu_plik;
    private javax.swing.JMenu am_jMenu_tool;
    private javax.swing.JPanel am_jPanel;
    private javax.swing.JTextField am_jTextField_l1;
    private javax.swing.JTextField am_jTextField_l2;
    private javax.swing.JTextField am_jTextField_wynik;
    // End of variables declaration//GEN-END:variables
}
