

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class wlasnyprojektma extends javax.swing.JFrame {

    /**
     * Creates new form wlasnyprojektma
     */
    public wlasnyprojektma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        am_jPanel = new javax.swing.JPanel();
        am_jLabel_info2 = new javax.swing.JLabel();
        am_jLabel_info1 = new javax.swing.JLabel();
        am_jLabel_rate3 = new javax.swing.JLabel();
        am_jLabel_info3 = new javax.swing.JLabel();
        am_jComboBox_rate = new javax.swing.JComboBox<>();
        am_jLabel_rate1 = new javax.swing.JLabel();
        am_jLabel_rate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        am_jLabel_rate2 = new javax.swing.JLabel();
        am_jRadioButton_ocena1 = new javax.swing.JRadioButton();
        am_jRadioButton_ocena2 = new javax.swing.JRadioButton();
        am_jRadioButton_ocena3 = new javax.swing.JRadioButton();
        am_jButton_send = new javax.swing.JButton();
        am_jMenuBar = new javax.swing.JMenuBar();
        am_jMenu_plik = new javax.swing.JMenu();
        am_jMenuItem_zapis = new javax.swing.JMenuItem();
        am_jMenuItem_wczytaj = new javax.swing.JMenuItem();
        am_jMenuItem_zamknij = new javax.swing.JMenuItem();
        am_jMenu_edycja = new javax.swing.JMenu();
        am_jMenuItem_czcionka = new javax.swing.JMenuItem();
        am_jMenuItem_tlo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        am_jMenuItem_program = new javax.swing.JMenuItem();
        am_jMenuItem_pomoc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikacja imienia Adama Manczaka");

        am_jPanel.setBackground(new java.awt.Color(51, 51, 51));

        am_jLabel_info2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        am_jLabel_info2.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_info2.setText("Funkcje nie działają.");

        am_jLabel_info1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        am_jLabel_info1.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_info1.setText("Witam w mojej Aplikacji!");

        am_jLabel_rate3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        am_jLabel_rate3.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_rate3.setText("Osobisty komentarz");

        am_jLabel_info3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        am_jLabel_info3.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_info3.setText("Dziękuje za wizyte!");

        am_jComboBox_rate.setBackground(new java.awt.Color(0, 255, 255));
        am_jComboBox_rate.setForeground(new java.awt.Color(0, 255, 255));
        am_jComboBox_rate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tak", "Nie" }));

        am_jLabel_rate1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        am_jLabel_rate1.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_rate1.setText("Autor: Adam Manczak");

        am_jLabel_rate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        am_jLabel_rate.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_rate.setText("Czy aplikacja sie panu spodobała?");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        am_jLabel_rate2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        am_jLabel_rate2.setForeground(new java.awt.Color(0, 255, 255));
        am_jLabel_rate2.setText("Ocena projektu");

        am_jRadioButton_ocena1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(am_jRadioButton_ocena1);
        am_jRadioButton_ocena1.setForeground(new java.awt.Color(0, 255, 255));
        am_jRadioButton_ocena1.setText("Brzydkie");
        am_jRadioButton_ocena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jRadioButton_ocena1ActionPerformed(evt);
            }
        });

        am_jRadioButton_ocena2.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(am_jRadioButton_ocena2);
        am_jRadioButton_ocena2.setForeground(new java.awt.Color(0, 255, 255));
        am_jRadioButton_ocena2.setText("Piękne");
        am_jRadioButton_ocena2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jRadioButton_ocena2ActionPerformed(evt);
            }
        });

        am_jRadioButton_ocena3.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(am_jRadioButton_ocena3);
        am_jRadioButton_ocena3.setForeground(new java.awt.Color(0, 255, 255));
        am_jRadioButton_ocena3.setText("Może być");
        am_jRadioButton_ocena3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jRadioButton_ocena3ActionPerformed(evt);
            }
        });

        am_jButton_send.setBackground(new java.awt.Color(0, 0, 0));
        am_jButton_send.setForeground(new java.awt.Color(0, 255, 255));
        am_jButton_send.setText("Wyślij Opinie");
        am_jButton_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jButton_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout am_jPanelLayout = new javax.swing.GroupLayout(am_jPanel);
        am_jPanel.setLayout(am_jPanelLayout);
        am_jPanelLayout.setHorizontalGroup(
            am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, am_jPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, am_jPanelLayout.createSequentialGroup()
                            .addComponent(am_jLabel_rate)
                            .addGap(159, 159, 159))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, am_jPanelLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(178, 178, 178))
                        .addGroup(am_jPanelLayout.createSequentialGroup()
                            .addComponent(am_jRadioButton_ocena1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(am_jRadioButton_ocena3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(am_jRadioButton_ocena2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, am_jPanelLayout.createSequentialGroup()
                        .addComponent(am_jLabel_rate3)
                        .addGap(216, 216, 216))))
            .addGroup(am_jPanelLayout.createSequentialGroup()
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(am_jPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(am_jLabel_info1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, am_jPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(am_jLabel_info3)
                            .addComponent(am_jLabel_info2))
                        .addGap(313, 313, 313))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, am_jPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(am_jButton_send)
                        .addGap(98, 98, 98)
                        .addComponent(am_jLabel_rate1))
                    .addGroup(am_jPanelLayout.createSequentialGroup()
                        .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(am_jPanelLayout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(am_jLabel_rate2))
                            .addGroup(am_jPanelLayout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(am_jComboBox_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        am_jPanelLayout.setVerticalGroup(
            am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(am_jPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(am_jLabel_info1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jLabel_info2)
                .addGap(80, 80, 80)
                .addComponent(am_jLabel_info3)
                .addGap(76, 76, 76)
                .addComponent(am_jLabel_rate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(am_jComboBox_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(am_jLabel_rate2)
                .addGap(18, 18, 18)
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(am_jRadioButton_ocena1)
                    .addComponent(am_jRadioButton_ocena2)
                    .addComponent(am_jRadioButton_ocena3))
                .addGap(31, 31, 31)
                .addComponent(am_jLabel_rate3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(am_jPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(am_jLabel_rate1))
                    .addGroup(am_jPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(am_jButton_send)))
                .addContainerGap())
        );

        am_jMenuBar.setBackground(new java.awt.Color(0, 0, 0));

        am_jMenu_plik.setText("Plik");
        am_jMenu_plik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jMenu_plikActionPerformed(evt);
            }
        });

        am_jMenuItem_zapis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        am_jMenuItem_zapis.setBackground(new java.awt.Color(0, 0, 0));
        am_jMenuItem_zapis.setText("Zapisz");
        am_jMenu_plik.add(am_jMenuItem_zapis);

        am_jMenuItem_wczytaj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        am_jMenuItem_wczytaj.setBackground(new java.awt.Color(0, 0, 0));
        am_jMenuItem_wczytaj.setText("Wczytaj");
        am_jMenu_plik.add(am_jMenuItem_wczytaj);

        am_jMenuItem_zamknij.setBackground(new java.awt.Color(0, 0, 0));
        am_jMenuItem_zamknij.setText("Zamknij program");
        am_jMenuItem_zamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jMenuItem_zamknijActionPerformed(evt);
            }
        });
        am_jMenuItem_zamknij.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                am_jMenuItem_zamknijKeyPressed(evt);
            }
        });
        am_jMenu_plik.add(am_jMenuItem_zamknij);

        am_jMenuBar.add(am_jMenu_plik);

        am_jMenu_edycja.setBackground(new java.awt.Color(0, 0, 0));
        am_jMenu_edycja.setText("Edycja");

        am_jMenuItem_czcionka.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        am_jMenuItem_czcionka.setBackground(new java.awt.Color(0, 0, 0));
        am_jMenuItem_czcionka.setText("Zmień czcionke");
        am_jMenu_edycja.add(am_jMenuItem_czcionka);

        am_jMenuItem_tlo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        am_jMenuItem_tlo.setBackground(new java.awt.Color(0, 0, 0));
        am_jMenuItem_tlo.setText("Zmień tło");
        am_jMenu_edycja.add(am_jMenuItem_tlo);

        am_jMenuBar.add(am_jMenu_edycja);

        jMenu3.setText("O programie");

        am_jMenuItem_program.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        am_jMenuItem_program.setBackground(new java.awt.Color(0, 0, 0));
        am_jMenuItem_program.setText("O programie");
        jMenu3.add(am_jMenuItem_program);

        am_jMenuItem_pomoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        am_jMenuItem_pomoc.setBackground(new java.awt.Color(0, 0, 0));
        am_jMenuItem_pomoc.setText("Pomoc");
        jMenu3.add(am_jMenuItem_pomoc);

        am_jMenuBar.add(jMenu3);

        setJMenuBar(am_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void am_jMenuItem_zamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jMenuItem_zamknijActionPerformed
    System.exit(0);
    }//GEN-LAST:event_am_jMenuItem_zamknijActionPerformed

    private void am_jRadioButton_ocena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jRadioButton_ocena1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_am_jRadioButton_ocena1ActionPerformed

    private void am_jRadioButton_ocena2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jRadioButton_ocena2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_am_jRadioButton_ocena2ActionPerformed

    private void am_jRadioButton_ocena3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jRadioButton_ocena3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_am_jRadioButton_ocena3ActionPerformed

    private void am_jMenuItem_zamknijKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_am_jMenuItem_zamknijKeyPressed
    
    }//GEN-LAST:event_am_jMenuItem_zamknijKeyPressed

    private void am_jMenu_plikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jMenu_plikActionPerformed
    
    }//GEN-LAST:event_am_jMenu_plikActionPerformed

    private void am_jButton_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jButton_sendActionPerformed
    System.exit(0);
    }//GEN-LAST:event_am_jButton_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wlasnyprojektma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wlasnyprojektma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wlasnyprojektma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wlasnyprojektma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wlasnyprojektma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton am_jButton_send;
    private javax.swing.JComboBox<String> am_jComboBox_rate;
    private javax.swing.JLabel am_jLabel_info1;
    private javax.swing.JLabel am_jLabel_info2;
    private javax.swing.JLabel am_jLabel_info3;
    private javax.swing.JLabel am_jLabel_rate;
    private javax.swing.JLabel am_jLabel_rate1;
    private javax.swing.JLabel am_jLabel_rate2;
    private javax.swing.JLabel am_jLabel_rate3;
    private javax.swing.JMenuBar am_jMenuBar;
    private javax.swing.JMenuItem am_jMenuItem_czcionka;
    private javax.swing.JMenuItem am_jMenuItem_pomoc;
    private javax.swing.JMenuItem am_jMenuItem_program;
    private javax.swing.JMenuItem am_jMenuItem_tlo;
    private javax.swing.JMenuItem am_jMenuItem_wczytaj;
    private javax.swing.JMenuItem am_jMenuItem_zamknij;
    private javax.swing.JMenuItem am_jMenuItem_zapis;
    private javax.swing.JMenu am_jMenu_edycja;
    private javax.swing.JMenu am_jMenu_plik;
    private javax.swing.JPanel am_jPanel;
    private javax.swing.JRadioButton am_jRadioButton_ocena1;
    private javax.swing.JRadioButton am_jRadioButton_ocena2;
    private javax.swing.JRadioButton am_jRadioButton_ocena3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
