/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.ad.rejestracjalogowanie;

import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author HP
 */
public class RejestracjaLogowanie extends javax.swing.JFrame {

    /**
     * Creates new form RejestracjaLogowanie
     */
    public RejestracjaLogowanie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        am_jPanel1 = new javax.swing.JPanel();
        am_jTabbedPane = new javax.swing.JTabbedPane();
        am_jPanel_rejestracja = new javax.swing.JPanel();
        am_jLabel_rejestracja = new javax.swing.JLabel();
        am_jTextField_name1 = new javax.swing.JTextField();
        am_jLabel_name1 = new javax.swing.JLabel();
        am_jLabel_mail1 = new javax.swing.JLabel();
        am_jTextField_mail1 = new javax.swing.JTextField();
        am_jLabel_pass1 = new javax.swing.JLabel();
        jTextField_pass1 = new javax.swing.JTextField();
        am_jLabel_pass_con = new javax.swing.JLabel();
        am_jTextField_pass_con = new javax.swing.JTextField();
        am_jButton_rejestracja = new javax.swing.JButton();
        am_jPanel_login = new javax.swing.JPanel();
        am_jLabel_logowanie = new javax.swing.JLabel();
        am_jLabel_mail2 = new javax.swing.JLabel();
        am_jTextField_mail2 = new javax.swing.JTextField();
        am_jLabel_pass2 = new javax.swing.JLabel();
        am_jTextField_pass2 = new javax.swing.JTextField();
        am_jButton_zaloguj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        am_jLabel_rejestracja.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        am_jLabel_rejestracja.setText("Rejestracja");

        am_jLabel_name1.setText("Username");

        am_jLabel_mail1.setText("Email");

        am_jLabel_pass1.setText("Password");

        am_jLabel_pass_con.setText("Confirm Password");

        am_jButton_rejestracja.setText("Rejestracja");
        am_jButton_rejestracja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jButton_rejestracjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout am_jPanel_rejestracjaLayout = new javax.swing.GroupLayout(am_jPanel_rejestracja);
        am_jPanel_rejestracja.setLayout(am_jPanel_rejestracjaLayout);
        am_jPanel_rejestracjaLayout.setHorizontalGroup(
            am_jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(am_jPanel_rejestracjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(am_jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(am_jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(am_jLabel_rejestracja)
                        .addComponent(am_jLabel_name1)
                        .addComponent(am_jLabel_mail1)
                        .addComponent(am_jTextField_mail1)
                        .addComponent(am_jLabel_pass1)
                        .addComponent(jTextField_pass1)
                        .addComponent(am_jLabel_pass_con)
                        .addComponent(am_jTextField_pass_con, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                        .addComponent(am_jTextField_name1))
                    .addComponent(am_jButton_rejestracja))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        am_jPanel_rejestracjaLayout.setVerticalGroup(
            am_jPanel_rejestracjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(am_jPanel_rejestracjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(am_jLabel_rejestracja)
                .addGap(13, 13, 13)
                .addComponent(am_jLabel_name1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jTextField_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jLabel_mail1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jTextField_mail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(am_jLabel_pass1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(am_jLabel_pass_con)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jTextField_pass_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(am_jButton_rejestracja)
                .addContainerGap())
        );

        am_jTabbedPane.addTab("Rejestracja", am_jPanel_rejestracja);

        am_jLabel_logowanie.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        am_jLabel_logowanie.setText("Logowanie");

        am_jLabel_mail2.setText("Email");

        am_jLabel_pass2.setText("Password");

        am_jButton_zaloguj.setText("Zaloguj");

        javax.swing.GroupLayout am_jPanel_loginLayout = new javax.swing.GroupLayout(am_jPanel_login);
        am_jPanel_login.setLayout(am_jPanel_loginLayout);
        am_jPanel_loginLayout.setHorizontalGroup(
            am_jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(am_jPanel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(am_jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(am_jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(am_jLabel_logowanie)
                        .addComponent(am_jLabel_mail2)
                        .addComponent(am_jLabel_pass2)
                        .addComponent(am_jTextField_mail2)
                        .addComponent(am_jTextField_pass2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                    .addComponent(am_jButton_zaloguj))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        am_jPanel_loginLayout.setVerticalGroup(
            am_jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(am_jPanel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(am_jLabel_logowanie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(am_jLabel_mail2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jTextField_mail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(am_jLabel_pass2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(am_jTextField_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(am_jButton_zaloguj)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        am_jTabbedPane.addTab("Logowanie", am_jPanel_login);

        javax.swing.GroupLayout am_jPanel1Layout = new javax.swing.GroupLayout(am_jPanel1);
        am_jPanel1.setLayout(am_jPanel1Layout);
        am_jPanel1Layout.setHorizontalGroup(
            am_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jTabbedPane)
        );
        am_jPanel1Layout.setVerticalGroup(
            am_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void am_jButton_rejestracjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jButton_rejestracjaActionPerformed
        try{
            FileWriter fw = new FileWriter("sekretnehasla.csv",true);
            String str = am_jTextField_name1.getText()+":"+am_jTextField_mail1.getText()+":"+jTextField_pass1.getText();
            fw.write(str);
            fw.close();
        }catch(IOException ex){
        }
    }//GEN-LAST:event_am_jButton_rejestracjaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RejestracjaLogowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RejestracjaLogowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RejestracjaLogowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RejestracjaLogowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RejestracjaLogowanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton am_jButton_rejestracja;
    private javax.swing.JButton am_jButton_zaloguj;
    private javax.swing.JLabel am_jLabel_logowanie;
    private javax.swing.JLabel am_jLabel_mail1;
    private javax.swing.JLabel am_jLabel_mail2;
    private javax.swing.JLabel am_jLabel_name1;
    private javax.swing.JLabel am_jLabel_pass1;
    private javax.swing.JLabel am_jLabel_pass2;
    private javax.swing.JLabel am_jLabel_pass_con;
    private javax.swing.JLabel am_jLabel_rejestracja;
    private javax.swing.JPanel am_jPanel1;
    private javax.swing.JPanel am_jPanel_login;
    private javax.swing.JPanel am_jPanel_rejestracja;
    private javax.swing.JTabbedPane am_jTabbedPane;
    private javax.swing.JTextField am_jTextField_mail1;
    private javax.swing.JTextField am_jTextField_mail2;
    private javax.swing.JTextField am_jTextField_name1;
    private javax.swing.JTextField am_jTextField_pass2;
    private javax.swing.JTextField am_jTextField_pass_con;
    private javax.swing.JTextField jTextField_pass1;
    // End of variables declaration//GEN-END:variables
}
