/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.manczakadam_gridlayout;

/**
 *
 * @author adame
 */
public class GridLayout extends javax.swing.JFrame {

    /**
     * Creates new form GridLayout
     */
    public GridLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_wynik = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton_mc = new javax.swing.JButton();
        jButton_mplus = new javax.swing.JButton();
        jButton_mminus = new javax.swing.JButton();
        jButton_cofnij = new javax.swing.JButton();
        jButton_c = new javax.swing.JButton();
        jButton_dzielenie = new javax.swing.JButton();
        jButton_mnozenie = new javax.swing.JButton();
        jButton_potega = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_pierwiastek = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_minus = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_plus = new javax.swing.JButton();
        jButton_procent = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_kropka = new javax.swing.JButton();
        jButton_wynik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jTextField_wynik.setEditable(false);
        jTextField_wynik.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_wynik.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jTextField_wynik.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_wynik.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(jTextField_wynik);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridLayout(6, 3, 4, 4));

        jButton_mc.setBackground(new java.awt.Color(51, 51, 51));
        jButton_mc.setForeground(new java.awt.Color(255, 255, 255));
        jButton_mc.setText("mc");
        jPanel2.add(jButton_mc);

        jButton_mplus.setBackground(new java.awt.Color(51, 51, 51));
        jButton_mplus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_mplus.setText("m+");
        jPanel2.add(jButton_mplus);

        jButton_mminus.setBackground(new java.awt.Color(51, 51, 51));
        jButton_mminus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_mminus.setText("m-");
        jPanel2.add(jButton_mminus);

        jButton_cofnij.setBackground(new java.awt.Color(51, 51, 51));
        jButton_cofnij.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cofnij.setText("<-");
        jPanel2.add(jButton_cofnij);

        jButton_c.setBackground(new java.awt.Color(0, 0, 0));
        jButton_c.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_c.setForeground(new java.awt.Color(255, 255, 255));
        jButton_c.setText("C");
        jButton_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_c);

        jButton_dzielenie.setBackground(new java.awt.Color(0, 0, 0));
        jButton_dzielenie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_dzielenie.setForeground(new java.awt.Color(255, 255, 255));
        jButton_dzielenie.setText("/");
        jPanel2.add(jButton_dzielenie);

        jButton_mnozenie.setBackground(new java.awt.Color(0, 0, 0));
        jButton_mnozenie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_mnozenie.setForeground(new java.awt.Color(255, 255, 255));
        jButton_mnozenie.setText("X");
        jPanel2.add(jButton_mnozenie);

        jButton_potega.setBackground(new java.awt.Color(51, 51, 51));
        jButton_potega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_potega.setForeground(new java.awt.Color(255, 255, 255));
        jButton_potega.setText("x²");
        jPanel2.add(jButton_potega);

        jButton_7.setBackground(new java.awt.Color(0, 0, 0));
        jButton_7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_7.setForeground(new java.awt.Color(255, 255, 255));
        jButton_7.setText("7");
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_7);

        jButton_8.setBackground(new java.awt.Color(0, 0, 0));
        jButton_8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_8.setForeground(new java.awt.Color(255, 255, 255));
        jButton_8.setText("8");
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_8);

        jButton_9.setBackground(new java.awt.Color(0, 0, 0));
        jButton_9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_9.setForeground(new java.awt.Color(255, 255, 255));
        jButton_9.setText("9");
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_9);

        jButton_pierwiastek.setBackground(new java.awt.Color(51, 51, 51));
        jButton_pierwiastek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_pierwiastek.setForeground(new java.awt.Color(255, 255, 255));
        jButton_pierwiastek.setText("√");
        jPanel2.add(jButton_pierwiastek);

        jButton_4.setBackground(new java.awt.Color(0, 0, 0));
        jButton_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_4.setForeground(new java.awt.Color(255, 255, 255));
        jButton_4.setText("4");
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_4);

        jButton_5.setBackground(new java.awt.Color(0, 0, 0));
        jButton_5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_5.setForeground(new java.awt.Color(255, 255, 255));
        jButton_5.setText("5");
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_5);

        jButton_6.setBackground(new java.awt.Color(0, 0, 0));
        jButton_6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_6.setForeground(new java.awt.Color(255, 255, 255));
        jButton_6.setText("6");
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_6);

        jButton_minus.setBackground(new java.awt.Color(51, 51, 51));
        jButton_minus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_minus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_minus.setText("-");
        jPanel2.add(jButton_minus);

        jButton_1.setBackground(new java.awt.Color(0, 0, 0));
        jButton_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_1.setText("1");
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_1);

        jButton_2.setBackground(new java.awt.Color(0, 0, 0));
        jButton_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_2.setText("2");
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_2);

        jButton_3.setBackground(new java.awt.Color(0, 0, 0));
        jButton_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_3.setForeground(new java.awt.Color(255, 255, 255));
        jButton_3.setText("3");
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_3);

        jButton_plus.setBackground(new java.awt.Color(51, 51, 51));
        jButton_plus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_plus.setForeground(new java.awt.Color(255, 255, 255));
        jButton_plus.setText("+");
        jPanel2.add(jButton_plus);

        jButton_procent.setBackground(new java.awt.Color(0, 0, 0));
        jButton_procent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_procent.setForeground(new java.awt.Color(255, 255, 255));
        jButton_procent.setText("%");
        jPanel2.add(jButton_procent);

        jButton_0.setBackground(new java.awt.Color(0, 0, 0));
        jButton_0.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_0.setForeground(new java.awt.Color(255, 255, 255));
        jButton_0.setText("0");
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_0);

        jButton_kropka.setBackground(new java.awt.Color(0, 0, 0));
        jButton_kropka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_kropka.setForeground(new java.awt.Color(255, 255, 255));
        jButton_kropka.setText(".");
        jPanel2.add(jButton_kropka);

        jButton_wynik.setBackground(new java.awt.Color(102, 102, 102));
        jButton_wynik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_wynik.setForeground(new java.awt.Color(255, 255, 255));
        jButton_wynik.setText("=");
        jPanel2.add(jButton_wynik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
       String number;
       number = jTextField_wynik.getText() + jButton_7.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
       String number;
       number = jTextField_wynik.getText() + jButton_8.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
       String number;
       number = jTextField_wynik.getText() + jButton_9.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
       String number;
       number = jTextField_wynik.getText() + jButton_4.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
       String number;
       number = jTextField_wynik.getText() + jButton_5.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
       String number;
       number = jTextField_wynik.getText() + jButton_6.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
       String number;
       number = jTextField_wynik.getText() + jButton_1.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
       String number;
       number = jTextField_wynik.getText() + jButton_2.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
       String number;
       number = jTextField_wynik.getText() + jButton_3.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        String number;
       number = jTextField_wynik.getText() + jButton_0.getText();
       jTextField_wynik.setText(number);
    }//GEN-LAST:event_jButton_0ActionPerformed

    private void jButton_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cActionPerformed
       jTextField_wynik.setText("");
    }//GEN-LAST:event_jButton_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GridLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GridLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GridLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GridLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GridLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_c;
    private javax.swing.JButton jButton_cofnij;
    private javax.swing.JButton jButton_dzielenie;
    private javax.swing.JButton jButton_kropka;
    private javax.swing.JButton jButton_mc;
    private javax.swing.JButton jButton_minus;
    private javax.swing.JButton jButton_mminus;
    private javax.swing.JButton jButton_mnozenie;
    private javax.swing.JButton jButton_mplus;
    private javax.swing.JButton jButton_pierwiastek;
    private javax.swing.JButton jButton_plus;
    private javax.swing.JButton jButton_potega;
    private javax.swing.JButton jButton_procent;
    private javax.swing.JButton jButton_wynik;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_wynik;
    // End of variables declaration//GEN-END:variables
}
