/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.ad.sprawdzian;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Sprawdzian extends javax.swing.JFrame {

    /**
     * Creates new form Sprawdzian
     */
    public Sprawdzian() {
        initComponents();
        addKeyListenerToam_jTextField_szblon();
        addKeyListenerToam_jTextField_cyfry();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        am_jPanel = new javax.swing.JPanel();
        am_jLabel_tablica = new javax.swing.JLabel();
        am_jLabel_szablon = new javax.swing.JLabel();
        am_jLabel_cyfry = new javax.swing.JLabel();
        am_jTextField_szablon = new javax.swing.JTextField();
        am_jTextField_cyfry = new javax.swing.JTextField();
        am_jButton_zapis = new javax.swing.JButton();
        am_jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        am_jPanel.setBackground(new java.awt.Color(255, 255, 102));

        am_jLabel_tablica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        am_jLabel_tablica.setText("Tablica Rejestracyjna");

        am_jLabel_szablon.setText("Pierwszy szablon");

        am_jLabel_cyfry.setText("Cyfry");

        am_jTextField_szablon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        am_jTextField_szablon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        am_jTextField_cyfry.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        am_jButton_zapis.setText("Zapisz");
        am_jButton_zapis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                am_jButton_zapisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout am_jPanelLayout = new javax.swing.GroupLayout(am_jPanel);
        am_jPanel.setLayout(am_jPanelLayout);
        am_jPanelLayout.setHorizontalGroup(
            am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(am_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(am_jLabel_tablica)
                    .addGroup(am_jPanelLayout.createSequentialGroup()
                        .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(am_jLabel_szablon)
                            .addComponent(am_jTextField_szablon, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(am_jLabel_cyfry)
                            .addComponent(am_jTextField_cyfry, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, am_jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(am_jButton_zapis, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        am_jPanelLayout.setVerticalGroup(
            am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(am_jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(am_jLabel_tablica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(am_jLabel_szablon)
                    .addComponent(am_jLabel_cyfry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(am_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(am_jTextField_szablon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(am_jTextField_cyfry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(am_jButton_zapis)
                .addContainerGap())
        );

        jMenu1.setText("File");
        am_jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        am_jMenuBar1.add(jMenu2);

        setJMenuBar(am_jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(am_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void am_jButton_zapisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_am_jButton_zapisActionPerformed
        try{
            FileWriter fw = new FileWriter("adam_manczak.txt",true);
            String str = am_jTextField_szablon.getText()+"/"+am_jTextField_cyfry.getText()+"\n";
            fw.write(str);
            fw.close();
            am_jTextField_szablon.setText("");
            am_jTextField_cyfry.setText("");
        }catch(IOException ex){
        }
    }//GEN-LAST:event_am_jButton_zapisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sprawdzian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sprawdzian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sprawdzian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sprawdzian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sprawdzian().setVisible(true);
            }
        });
    }
    
        private void addKeyListenerToam_jTextField_szblon(){
        am_jTextField_szablon.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch == 'a' || ch == 'A' || ch == 'b' || ch == 'B' || ch == 'c' || ch == 'C' || ch == 'd' || ch == 'D' || ch == 'e' || ch == 'E' || ch == 'f' || ch == 'F' || ch == '-' ||ch == KeyEvent.VK_BACK_SPACE){
                    am_jTextField_szablon.setEditable(true);
                } else {
                    am_jTextField_szablon.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
               
            }
        });
        
    }
        
        private void addKeyListenerToam_jTextField_cyfry(){
        am_jTextField_cyfry.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch == '0' || ch == '1' || ch == '2' || ch == '3' || ch == '4' || ch == '5' || ch == '6' || ch == '7' || ch == '8' || ch == '9' || ch == KeyEvent.VK_BACK_SPACE){
                    am_jTextField_cyfry.setEditable(true);
                } else {
                    am_jTextField_cyfry.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
               
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton am_jButton_zapis;
    private javax.swing.JLabel am_jLabel_cyfry;
    private javax.swing.JLabel am_jLabel_szablon;
    private javax.swing.JLabel am_jLabel_tablica;
    private javax.swing.JMenuBar am_jMenuBar1;
    private javax.swing.JPanel am_jPanel;
    private javax.swing.JTextField am_jTextField_cyfry;
    private javax.swing.JTextField am_jTextField_szablon;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
